--- #YAML:1.0
name:                XML-OPML-SimpleGen
version:             0.03
abstract:            create OPML using XML::Simple
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Accessor:               0
    Test::More:                    0
    version:                       0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Marcus Thiesen <marcus@thiesen.org>
